# Generated by Django 2.2.13 on 2021-07-29 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=32)),
                ('car_model_name', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('E', 'engine'), ('FS', 'fuel system'), ('EX_S', 'exhaust system'), ('CS', 'cooling system'), ('LS', 'lubrication system'), ('EL_S', 'electrical system'), ('T', 'transmission'), ('C', 'chassis')], max_length=20)),
                ('description', models.TextField()),
                ('is_new', models.BooleanField(default=False)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
