# Generated by Django 2.2.13 on 2021-08-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_parts', '0003_auto_20210805_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_parts.Buyer')),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_parts.CarPart')),
            ],
        ),
    ]
